services:
  database:
    container_name: database
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ../database/data/mysql/:/var/lib/mysql

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile_application
    environment:
      - PORT=${API_PORT}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    entrypoint:
      sh /app/entrypoint.sh
    ports:
      - ${API_PORT}:${API_PORT}
    working_dir: /app
    volumes:
      - ../application/app/:/app
    # stdin_open: true
    # tty: true

  presentation:
    container_name: presentation
    image: httpd:2.4.59-alpine
    volumes:
      - ../presentation/htdocs:/usr/local/apache2/htdocs
    ports:
      - 80:80
